In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.2.2)
Requirement already satisfied: bleach in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (0.1.30)
Requirement already satisfied: packaging in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (7.35.0)
Requirement already satisfied: python-dateutil in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (4.68.2)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from nbformat->jupytext->kaggle) (5.15.1)
Requirement already satisfied: attrs>=22.2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil->kaggle) (1.16.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (3.17)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kaggle

In [3]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets -f Walmart.csv

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [4]:
!kaggle datasets download -d najir0123/walmart-10k-sales-datasets -f Walmart.csv

Dataset URL: https://www.kaggle.com/datasets/najir0123/walmart-10k-sales-datasets
License(s): MIT
Downloading Walmart.csv to C:\Users\User\Downloads\WALMART_PYTHON+SQL

  0%|          | 0.00/819k [00:00<?, ?B/s]
100%|##########| 819k/819k [00:01<00:00, 466kB/s]
100%|##########| 819k/819k [00:01<00:00, 465kB/s]

In [5]:
import zipfile

zip_ref = zipfile.ZipFile('Walmart.csv.zip') 

zip_ref.extractall() # extract file to dir

zip_ref.close()

FileNotFoundError: [Errno 2] No such file or directory: 'Walmart.csv.zip'

In [6]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Walmart.csv', 'WALMARTSALES ANALSYS.ipynb']

In [7]:
import pandas as pd
df = pd.read_csv("Walmart.csv")

In [8]:
df

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [9]:
df.shape

(10051, 11)

In [10]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [11]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 1.4 MB

In [13]:
df.duplicated().sum()

np.int64(51)

In [14]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [15]:
df.shape

(10000, 11)

In [16]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [17]:

df.dropna(inplace=True) #droppping all rows with missing records

# verify
df.isnull().sum() # verify

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [18]:
df.shape

(9969, 11)

In [19]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [20]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [22]:
df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)

In [23]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price        float64
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [24]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 1.5 MB

In [26]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [27]:
df['total Price'] = df['unit_price'] * df['quantity']

In [28]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total Price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [29]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin',
       'total Price'],
      dtype='str')

In [30]:
df.columns = df.columns.str.lower()
df.columns   #Fixing the column name to lower case

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin',
       'total price'],
      dtype='str')

In [31]:
df.shape

(9969, 12)

In [32]:
df.to_csv('walmart_clean_data.csv', index=False)

In [33]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (5.3.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import pyodbc
print(pyodbc.version)

5.3.0

In [35]:
import sqlalchemy as sal

engine = sal.create_engine(
    "mssql+pyodbc://LAPTOP-4L14UMHG\\SQLEXPRESS/master?driver=ODBC+Driver+17+for+SQL+Server"
)

conn = engine.connect()

print("Connected Successfully!")

Connected Successfully!

In [36]:
df.to_sql(name='walmart', con=engine_mysql, if_exists='append', index=False)

NameError: name 'engine_mysql' is not defined

In [37]:
df.to_sql('walmart', con=conn , index=False, if_exists = 'append')

51

In [38]:
df

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,WALM056,Rowlett,Fashion accessories,37.00,3.0,03/08/23,10:10:00,Cash,3.0,0.33,111.00
9996,9997,WALM030,Richardson,Home and lifestyle,58.00,2.0,22/02/21,14:20:00,Cash,7.0,0.48,116.00
9997,9998,WALM050,Victoria,Fashion accessories,52.00,3.0,15/06/23,16:00:00,Credit card,4.0,0.48,156.00
9998,9999,WALM032,Tyler,Home and lifestyle,79.00,2.0,25/02/21,12:25:00,Cash,7.0,0.48,158.00
9999,10000,WALM069,Rockwall,Fashion accessories,62.00,3.0,26/09/20,9:48:00,Cash,3.0,0.33,186.00

In [39]:
df.dtypes

invoice_id          int64
branch                str
city                  str
category              str
unit_price        float64
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
total price       float64
dtype: object